locale                   : "zh-CN"
title                    : "LINOTES"
title_separator          : "-"
name                     : "Hawk Zhang"
url                      : "https://linotes.netlify.com"
email: imhawkz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  用简洁清晰的语言讨论技术




#search                   : true # false (default)
#search_full_content      : true # false (default)







# Theme
theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"




category_archive:
  type: liquid
  path: /categories/




plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll/tagging


whitelist:
  - jekyll-feed
  - jekyll-paginate
  - jekyll/tagging




permalink: /:categories/:title/
paginate: 15 # amount of posts to show
paginate_path: /page:num/





# tags
tag_page_layout: tag
tag_page_dir: tag






# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: true
      sidebar:
        nav: "linux"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true








# Site Author
author:
  name             : "Hawk Zhang"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : # "用简洁清晰的语言讨论技术"
  location         : "北京"
  email            : "imhawkz@gmail.com"
  home             : # null (default), "absolute or relative url to link to author home"
  linkedin         : "hawkzhang"








# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
