locale                   : "zh-CN"
title                    : "LINOTES"
title_separator          : "-"
name                     : "Hawk Zhang"
url                      : "https://linotes.imliloli.com"
email: imhawkz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  用简洁清晰的语言讨论技术
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: liloli
github_username:  linotes



# Build settings
markdown: kramdown



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false




# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false






# Theme
theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

sass:
  sass_dir: _sass
  style: compressed



category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/



plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll/tagging


whitelist:
  - jekyll-feed
  - jekyll-paginate
  - jekyll/tagging



permalink: /:categories/:title/
paginate: 15 # amount of posts to show
paginate_path: /page:num/








tag_page_layout: tag
tag_page_dir: tag







include: ["_pages"]

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      sidebar:
        nav: "linux"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true








# Site Author
author:
  name             : "Hawk Zhang"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : # "用简洁清晰的语言讨论技术"
  location         : "北京"
  email            : "imhawkz@gmail.com"
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : ""
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "hawkzhang"
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          : ""
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"




# comments
comments:
  provider               : "staticman"
staticman:
  allowedFields          : ['name', 'email', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"











# Social Sharing
#twitter:
#  username               : "liloli"
#facebook:
#  username               : "lilolibj"








# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
